[package]
name = "mauricebarnum-oxia-client"
version = "0.1.0"
edition.workspace = true
license = "Apache-2.0"

[dependencies]
mauricebarnum-oxia-common = { path = "../common" }
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
tonic = { version = "0.14.2", features = ["gzip", "channel", "zstd"] }
prost = "0.14.1" # If using Protobuf
thiserror = "2.0.17"
bytes = "1.10.1"
futures-util = "0.3.31"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = [
    "env-filter",
    "fmt",
    "registry",
] }

async-trait = "0.1.89"
futures = "0.3.31"
getrandom = "0.3.4"
rand = "0.9.2"
xxhash-rust = { version = "0.8.15", default-features = false, features = [
    "xxh3",
] }
backon = "1.6.0"

[dev-dependencies]
chrono = "0.4.42"
socket2 = "0.6.1"
test-log = { version = "0.2.18", features = ["trace", "color"] }
oxia-bin-util = { path = "../oxia-bin-util" }
tempfile = "3.23.0"
anyhow = "1.0.100"
itertools = "0.14.0"

[lints]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    "cfg(accept_invalid_shard_ids)",
] }


[package.metadata.cargo_check_external_types]
allowed_external_types = [
    "bytes::bytes::Bytes",
    "tonic::status::Status",
    "tonic::transport::error::Error",
    "futures_core::stream::Stream",
]
