[workspace]
members = ["oxia-bin-util", "cmd", "client", "common"]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
clone_on_ref_ptr = "deny"
missing_errors_doc = "allow"
must_use_candidate = "allow"
option_if_let_else = "allow"


[workspace.lints.rust]
private_interfaces = "deny"
unexpected_cfgs = { level = "warn", check-cfg = [
    "cfg(accept_invalid_shard_ids)",
] }

[profile.release]
opt-level = 3
debug = true
split-debuginfo = "packed"
strip = "none"
debug-assertions = false
overflow-checks = false
lto = true
panic = "unwind"
incremental = false
codegen-units = 1
rpath = false
